#!/bin/bash

docker run -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=Fender2000" \
   -p 1433:1433 --name sql1 --hostname sql1 \
   -d \
   --mount source=~/Workspace/angular-dotnet,target=/code,type=bind \
   mcr.microsoft.com/mssql/server:2022-latest